#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Elemental
version:      2.0
version_from: lib/XML/Elemental.pm
installdirs:  site
requires:
    Class::Accessor:               0
    XML::SAX:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
