#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Elemental
version:      1
version_from: lib/XML/Elemental.pm
installdirs:  site
requires:
    XML::Parser:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
